# Generated by Django 4.2.1 on 2023-05-16 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('anons', models.CharField(max_length=250, verbose_name='Анонс')),
                ('Full_text', models.TextField(verbose_name='Содержание')),
                ('data', models.DateField(verbose_name='Дата публикаций')),
            ],
        ),
    ]
